apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc
  labels:
    name: mymovies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mymovies
  template:
    metadata:
      labels:
        app: mymovies
    spec:
      containers:
      - name: mvc
        image: mymoviesmvc:v1
        env:
          - name: MyMoviesConnStr
            value: "Host=postgres;Port=5432;Database=MyMoviesDb;Username=postgres;Password=moviedbsecretpassword"
      restartPolicy: Always
