// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMoviesMvc.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MyMoviesMvc.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20200228140648_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MyMoviesMvc.DataModels.MovieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Director")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = -10,
                            Director = "Frank Darabont",
                            Title = "The Shawshank redemption",
                            Year = 1994
                        },
                        new
                        {
                            Id = -9,
                            Director = "Francis Ford Coppola",
                            Title = "The Godfather",
                            Year = 1972
                        },
                        new
                        {
                            Id = -8,
                            Director = "Christopher Nolan",
                            Title = "The Dark Knight",
                            Year = 2008
                        },
                        new
                        {
                            Id = -7,
                            Director = "Francis Ford Coppola",
                            Title = "The Godfather: Part II",
                            Year = 1974
                        },
                        new
                        {
                            Id = -6,
                            Director = "Peter Jackson",
                            Title = "The Lord of the Rings: The Return of the King",
                            Year = 2003
                        },
                        new
                        {
                            Id = -5,
                            Director = "Quentin Tarantino",
                            Title = "Pulp Fiction",
                            Year = 1994
                        },
                        new
                        {
                            Id = -4,
                            Director = "Steven Spielberg",
                            Title = "Schindler's List",
                            Year = 1993
                        },
                        new
                        {
                            Id = -3,
                            Director = "Sidney Lumet",
                            Title = "12 Angry Men",
                            Year = 1957
                        },
                        new
                        {
                            Id = -2,
                            Director = "Christopher Nolan",
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            Id = -1,
                            Director = "David Fincher",
                            Title = "Fight Club",
                            Year = 1999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
